### PR TITLE
Improve testing

### PR DESCRIPTION
**Pull request by ghoneycutt**
Explicity test against supported versions of Puppet. Modernize style and
allow spec tests to work.

### CODE REVIEW

**Comment by vikraman** [comment]
Since I haven't used puppet/ruby in a while, I'll leave this to @adrienthebo and @tampakrap.

**Comment by ghoneycutt** [comment]
Tests passed! I've rebased to squash the commits.

**Comment by tampakrap** [comment]
:+1:

**Comment by ghoneycutt** [comment]
@tampakrap @vikraman Could this please be merged?

**Comment by vikraman** [comment]
👍

**Comment by ghoneycutt** [comment]
Thanks everyone!

**Pull request merged**
