### PR TITLE
to fix  # is not a valid atom

### PR DESCRIPTION
**Pull request by samuraiii**
to fix error Error: Failed to apply catalog: # is not a valid atom

### CODE REVIEW

**Comment by vikraman** [comment]
Could you add a test case for this?

**Comment by samuraiii** [comment]
Is this enough?
https://github.com/gentoo/puppet-portage/issues/139

**Comment by vikraman** [comment]
I meant a unit test: `spec/unit/provider/package_keywords/parsed_spec.rb`

**Comment by samuraiii** [comment]
OK, I am sorry but I am ruby novice (I was able to craft some custom facts and that is all).
I am not really sure how to do it, and if this is necessary  for ignored line. 
I am just as good at puppet as to run computational farm configured with puppet, so if you can help me, or at last point me to right RTFM.
With thanks 
S

**Comment by robbat2** [comment]
Merged:
[master 6a56067] to fix  # is not a valid atom
 Author: samuraiii <samuraiii@users.noreply.github.com>
 Date: Mon May 2 19:47:50 2016 +0200
 1 file changed, 2 insertions(+), 1 deletion(-)

**Pull request closed without merging**
